### ISSUE TITLE
Linux compatibility

### ISSUE THREAD

**Issue by Figments** [tmthecoder/Argon2Swift#3]
Hello! Thank you for the fantastic library!

Unfortunately, the utilization of macOS-specific frameworks (specifically `Security`) prevents this library from being used on Linux for server environments, e.g. with Vapor APIs.

Is there any way this can be updated to be Linux-compatible?

**Comment by tmthecoder** [comment]
Update: v1.0.3 is now available as a tagged release. It has also been pushed to Cocoapods, so it is available via both SPM and Cocoapods.
